version: '3'
services:
  python3:
    restart: always
    build: .
    ports:
      - "8000:8000"
    container_name: 'codegym_academy'
    working_dir: '/root/'
    tty: true
    volumes:
      - ./project:/root/project
